# Generated by Django 5.2.4 on 2025-07-14 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_remove_venda_produto_remove_venda_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='data_vencimento',
        ),
    ]
